trigger:
- main

pool:
  name: 'RoniAgentFirst'  # Self-hosted agent pool name

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'TestAppAPI/TestAppAPI.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'TestAppAPI.Tests/TestAppAPI.Tests.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'TestAppAPI.Tests/TestAppAPI.Tests.csproj'
    arguments: '--configuration $(buildConfiguration) --filter FullyQualifiedName~TestAppAPI.Tests.Tests.Unit --logger trx --results-directory $(System.DefaultWorkingDirectory)/TestResults/UnitTests'
  continueOnError: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'TestAppAPI.Tests/TestAppAPI.Tests.csproj'
    arguments: '--configuration $(buildConfiguration) --filter FullyQualifiedName~TestAppAPI.Tests.Tests.Component --logger trx --results-directory $(System.DefaultWorkingDirectory)/TestResults/ComponentTests'
  continueOnError: true

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '$(System.DefaultWorkingDirectory)/TestResults/**/*.trx'
    mergeTestResults: true
    failTaskOnFailedTests: true
